/*******************************************************************************
 * XComSpawnPointNativeBase generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2013 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XComSpawnPointNativeBase extends Actor
    hidecategories(Navigation)
    native(Level)
    notplaceable;