/*******************************************************************************
 * XComCursorVolume generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2013 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XComCursorVolume extends Volume
    hidecategories(Navigation,Movement,Display)
    native
	placeable;

var()  int m_iFloorNumber;
var()  bool m_bTreatAsStair;
var()  bool m_bIgnoreHoles;

defaultproperties
{
    begin object name=BrushComponent0
        ReplacementPrimitive=none
    end object
   
    BrushComponent=BrushComponent0

    Components(0)=BrushComponent0
    bMovable=false
   
    CollisionComponent=BrushComponent0
}