/*******************************************************************************
 * XComDamageType_Plasma generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2013 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XComDamageType_Plasma extends XComDamageType
    hidecategories(Object)
    native(Weapon);


defaultproperties
{
    bCausesFire=true
    bCausesFracture=true
    DamagedFFWaveform=ForceFeedbackWaveform'Default__XComDamageType_Plasma.ForceFeedbackWaveform0'
    KilledFFWaveform=ForceFeedbackWaveform'Default__XComDamageType_Plasma.ForceFeedbackWaveform1'
}