/*******************************************************************************
 * XGSquad generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2013 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class XGSquad extends XGSquadNativeBase
    hidecategories(Navigation)
    notplaceable;
