/*******************************************************************************
 * SeqAct_RemoveActor generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib ? 2009-2013 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class SeqAct_SetCursorHide extends SequenceAction
    hidecategories(Object)
    forcescriptorder(true);


enum ENewBoolValue
{
    UNCHANGED,
    SET_FALSE,
	SET_TRUE
};
var() ENewBoolValue HideableWhenBlockingObjectOfInterest;
var() ENewBoolValue bIgnoreFor3DCursorCollision;

var() bool bChangeHidingPartner;
var() Actor HidingPartner;

var() Actor Target;

event Activated()
{
	if ( Target.IsA( 'XComLevelActor') )
	{
		if (HideableWhenBlockingObjectOfInterest 	!= UNCHANGED)		XComLevelActor(Target).HideableWhenBlockingObjectOfInterest  = HideableWhenBlockingObjectOfInterest		==SET_TRUE;
		if (bIgnoreFor3DCursorCollision 			!= UNCHANGED)		XComLevelActor(Target).bIgnoreFor3DCursorCollision 			= bIgnoreFor3DCursorCollision				==SET_TRUE;
	
		if (bChangeHidingPartner) XComLevelActor(Target).HidingPartner = HidingPartner;
	}
	else if (Target.IsA('XComFracLevelActor'))
	{
		if (HideableWhenBlockingObjectOfInterest 	!= UNCHANGED)		XComFracLevelActor(Target).HideableWhenBlockingObjectOfInterest  = HideableWhenBlockingObjectOfInterest		==SET_TRUE;
		if (bIgnoreFor3DCursorCollision 			!= UNCHANGED)		XComFracLevelActor(Target).bIgnoreFor3DCursorCollision 			= bIgnoreFor3DCursorCollision				==SET_TRUE;
	
		if (bChangeHidingPartner) XComFracLevelActor(Target).HidingPartner = HidingPartner;
	}
	
	ActivateOutputLink(0);
}

defaultproperties
{
    bCallHandler=false
	VariableLinks(0)=(ExpectedType=Class'Engine.SeqVar_Object',LinkDesc="Target",PropertyName=Target)
	VariableLinks(1)=(ExpectedType=Class'Engine.SeqVar_Object',LinkDesc="Hiding Partner",PropertyName=HidingPartner)
	
    ObjName="Set HideableWhenBlockingObjectOfInterest"
}